DROP TABLE IF EXISTS authors;
CREATE TABLE authors(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(255), SECOND_NAME VARCHAR(255));

DROP TABLE IF EXISTS genres;
CREATE TABLE genres(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, DESCRIPTION VARCHAR(255));


DROP TABLE IF EXISTS books;
CREATE TABLE books(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(255),
AUTHOR_ID BIGINT NOT NULL,
GENRE_ID BIGINT NOT NULL,
CONSTRAINT books_authors_fk
FOREIGN KEY (AUTHOR_ID) REFERENCES authors (ID) ON DELETE CASCADE,
CONSTRAINT books_genres_fk
FOREIGN KEY (GENRE_ID) REFERENCES genres (ID) ON DELETE CASCADE
);